name = "zikr-app"
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist"

[env.production]
# D1 Database binding (you'll get the database_id after creating the database)
[[env.production.d1_databases]]
binding = "DB"
database_name = "zikr-database"
database_id = "YOUR_DATABASE_ID_HERE"

# KV Namespace for translations (you'll get the id after creating the namespace)
[[env.production.kv_namespaces]]
binding = "TRANSLATIONS"
id = "YOUR_KV_NAMESPACE_ID_HERE"

# Environment variables for production
[env.production.vars]
ENVIRONMENT = "production"

# Preview/staging environment
[env.preview]
[[env.preview.d1_databases]]
binding = "DB"
database_name = "zikr-database-preview"
database_id = "YOUR_PREVIEW_DATABASE_ID_HERE"

[[env.preview.kv_namespaces]]
binding = "TRANSLATIONS"
id = "YOUR_PREVIEW_KV_NAMESPACE_ID_HERE"

[env.preview.vars]
ENVIRONMENT = "preview"